# Generated by Django 3.2.13 on 2022-06-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empenho', models.IntegerField()),
                ('Nota_Fiscal', models.IntegerField()),
                ('Material', models.CharField(max_length=150)),
                ('Data', models.DateField(blank=True, null=True, verbose_name='data')),
                ('Obs', models.CharField(max_length=150)),
            ],
        ),
    ]
